### ISSUE TITLE
Static and dynamic route

### ISSUE THREAD

**Issue by yvzshn** [izniburak/php-router#1]
hi Burak, 
before thank you for class.
how to catch and use this examples;
/company/[regex] ? 
or
/[regex]

**Comment by izniburak** [comment]
I'll add as soon as the documentation.

But, it may simply be as follows:

**{a}** => all characters (No slash "/")
**{d}** => only decimal number (0-9)
**{s}** => only letter (a-zA-Z)
**{u}** => only characters that are supported for URLs. (a-zA-Z0-9_-) So, SEF URL.
**{*}** => All characters

In addition; you can also add your own filters.
Example;

```php
$router->pattern("lowercase", "[a-z]+");
$router->get("/test/{lowercase}", function($param){
    // bla bla bla...
} );
$router->run();
```
