### ISSUE TITLE
Parameter Patterns

### ISSUE THREAD

**Issue by dukinfotech** [izniburak/php-router#10]
Hi izniburak, thank your contribution for our community. I try using parameter patterns  feature. But it not working. It shows Object not found!. URL: '/' is working perfectly. Thank
$router->get('/', function() {
   echo 'Home';
});

$router->get('/{s}', function($value)
{
  echo 'Hello, ' . $value;
});

**Comment by peter279k** [comment]
@dukinfotech, thank you for your reply. I can use the parameter pattern successfully.

Here is my sample code:

```php
<?php

require __DIR__ . '/../../vendor/autoload.php';

use Buki\Router;

$params = [
    'paths' => [
        'controllers' => 'controllers/',
    ],
    'namespaces' => [
        'controllers' => 'Controllers\\',
    ],
    'base_folder' => __DIR__,
    'main_method' => 'main',
];

$router = new Router($params);

$router->get('/', function() {
    return 'Hello World!';
});


$router->get('/{s}', function() {
    return 'parameter pattern';
});

$router->get('/controllers', 'TestController@main');

$router->run();

```
You can save this file named `server.php` and run `php -S localhost:5000 tests/fixtures/server.php` and type the `localhost:3000/string` url on the browser.

I use the `php-7.2` to complete this work.

Can you reproduce issue? Thanks.

**Comment by dukinfotech** [comment]
The same issue in Klein package (https://github.com/klein/klein.php). And the solution is insert this code $base  = dirname($_SERVER['PHP_SELF']);

// Update request when we have a subdirectory
if (ltrim($base, '/'))
{
   $_SERVER['REQUEST_URI'] = substr($_SERVER['REQUEST_URI'], strlen($base));
}
But i don't like klein for my small project. I tried apply for this package but it still not working. Sorry for my English.

**Comment by dukinfotech** [comment]
I find out why it not working. My project is subdir: htdocs/mvc-base. But i don't know how to fix

**Comment by peter279k** [comment]
@dukinfotech, you have to change  the original web document root to `htdocs/mvc-base`.

And it will be worked fine.

It looks like you use the XAMPP server?

**Comment by dukinfotech** [comment]
> It looks like you use the XAMPP server?

Yes. i'm using xampp

**Comment by izniburak** [comment]
@dukinfotech Are you sure that you set base_folder value in configuration parameters correctly?

**Comment by peter279k** [comment]
@izniburak, I think it's not related to the `base_folder` problem.

This issue is about the `Deployment`. To solve this issue, it should have the build/deployment tutorial.

**Comment by peter279k** [comment]
BTW, I also deploy this router with Apache server on Ubuntu 16.04 successfully.

It's about the internal Apache setting, including `.htaccess` setting and `rewrite`.

**Comment by izniburak** [comment]
I guess so. Rewrite module must be enable for Apache on the server. After that, .htaccess file must be add. Documentation may help to you. 
https://github.com/izniburak/php-router/wiki/2.-Getting-Started#quick-usage

I just made a new test to make sure. No problem occurred.
