### ISSUE TITLE
Warning on other methods

### ISSUE THREAD

**Issue by bramaudi** [izniburak/php-router#12]
I only use GET & POST method before, but now when i try to make restful api i had a problem with the other methods like PUT, PATCH, and DELETE, it show a warning like this

**Warning**:  preg_match(): Compilation failed: missing ) at offset 12 in
**../myproject/vendor/izniburak/router/src/Router.php** on line
**299**

**Comment by peter279k** [comment]
@bramaudi, thank you for your reply. Can you reproduce issue?

Including development environment, sample code and so on.

Thanks.

**Comment by izniburak** [comment]
@bramaudi What's your route definition? Can you share?

**Comment by bramaudi** [comment]
My route file:
$router->put('/posts/{i}', function(){
 return 1;
});
~ running with built-in php server on Ubuntu

**Comment by bramaudi** [comment]
Hmm, just mistake typing, lol. But  thank you so much for your reply.
