### ISSUE TITLE
AJAX request not working with jquery

### ISSUE THREAD

**Issue by dukinfotech** [izniburak/php-router#13]
I trying ajax request from jquery, but router return 404 (not found), i also tried either get method or post method

**Comment by peter279k** [comment]
Hi @dukinfotech, thank you for your reply.

Can you reproduce issue?

Could you provide the jQuery and PHP code that you run?

**Comment by dukinfotech** [comment]
this is my jquery code:
$.get('schools', function (data) {
  console.log(data);
});
and this is my PHP code:
$router->get('schools', function () {
    echo 123;
});
tks for support

**Comment by peter279k** [comment]
@dukinfotech, thank you for your sample code.

Do you refer the [Example Usage](https://github.com/izniburak/php-router#example-usage) section on `README`?

The sample PHP code that you provide seems to be incorrect.

Please use the sample code on `README` and try again.

Thanks.

**Comment by dukinfotech** [comment]
Other routes are working but just ajax request is not working

**Comment by peter279k** [comment]
@dukinfotech, I will try that if having available time.

**Comment by izniburak** [comment]
Hi @dukinfotech ,
Do you have still this problem? I tried, but I could not get any error. I'll review again in detail.
