### ISSUE TITLE
Middleware usage

### ISSUE THREAD

**Issue by jaysonvacaro** [izniburak/php-router#14]
How can I use the middleware for this.

**Comment by peter279k** [comment]
@izniburak, I also don't have the current tutorial about `Middleware` usage.

Could you concern about this? Thanks :).

**Comment by izniburak** [comment]
Hi @jaysonvacaro , @peter279k 
I had not been have any time to update documentation but I'm gonna update documentation of middleware and controller detailed in this week. 
Thank!

**Comment by peter279k** [comment]
Hi @izniburak, thanks for your reply.

Hopefully you update the `Middleware` usage in `README` :).

**Comment by izniburak** [comment]
Hi @jaysonvacaro , @peter279k 
I've just updated Controller and Middleware documentation. You can check Wiki page. 
I will also update README for this ASAP.
