### ISSUE TITLE
"Custom 404 handling" anlayamadım.

### ISSUE THREAD

**Issue by velierdincsalar** [izniburak/php-router#16]
Merhaba Burak

Custom 404 handling bunu anlıyamadım. route bulamayınca 404 sayfasına nasıl yönlendireceğim ?

**Comment by izniburak** [comment]
Router içerisinde bulunan `error` metodunu kullanabilirsiniz. Bu metot parametre olarak bir Closure function alır. Örneğin:
```php
$route->error(function() {
  // Route bulunamadığında yapılacak işlemler.
  // Hata sayfası gösterme, başka bir sayfaya yönlendirme vs... 
});
```

**Comment by velierdincsalar** [comment]
Çok Teşekkürler
