### ISSUE TITLE
PSR-4 not supported

### ISSUE THREAD

**Issue by KarelWintersky** [izniburak/php-router#18]
Output:
```
Opps! An error occurred.
SteamPunkEngine/Mobile/Index class is not found. Please, check file.
```
My routers:
```
$router->get('/', 'SteamPunkEngine\Mobile\Index@view_frontpage');
$router->post('/ajax/stats:updateVisitCount/', 'SteamPunkEngine\Mobile\Stats@invokeUpdateVisitCount');
```

My composer.json
```
"autoload": {
      "psr-4": {
        "SteamPunkEngine\\": "engine/"
      }
    }
```
File `Index.php` exists at `www/engine/Mobile/Index.php` and have valid namespace: `namespace SteamPunkEngine\Mobile;`

**Comment by izniburak** [comment]
Hi @KarelWintersky 
Could you please share a part of your code that contains directory structure and Router settings?

**Comment by KarelWintersky** [comment]
Router settings - none `[]`. 

Directory structure ( `.` is project root, composer.json here):
```
./engine
./engine/Mobile
./engine/Mobile/Index.php (namespace SteampunkEngine/Mobile)
./Engine/Mobile/Stats.php (namespace SteampunkEngine/Mobile)
./Engine/Mobile/Articles/Articles.php (namespace SteampunkEngine/Mobile/Articles)
and so on
```

Also, DIE from router is ugly code.

**Comment by izniburak** [comment]
Did you configure Router settings according to your application? You can check out this guide: https://github.com/izniburak/php-router/wiki/2.-Getting-Started#paths-and-namespaces

**Comment by KarelWintersky** [comment]
No. Your package MUST do it automatically. 

All my classes defined in global space and can be autoload with composer mechanism. 

Redundant configuration is redundant.

**Comment by izniburak** [comment]
Router can not know your route settings, controllers and middleware paths. Also their namespaces as well. There are a couple of way to define route with using Controller. You can only specify class name or full name (with namespace)

For example: TestController, Foo\Bar\TestController, Foo\Bar\TestController::class ... Therefore Router must know your paths. Maybe we can change and develop this behavior, i'm not sure now. But currently, you must define your configs correctly.

**Comment by KarelWintersky** [comment]
Something like this:
```
// from nikic/fast-route 

            list($state, $handler, $vars) = $routeInfo;
            list($class, $method) = explode('@', $handler, 2);
            
            if (class_exists($class) && method_exists($class, $method)) {
                call_user_func_array(array(new $class, $method), $vars);    
            } 
```

That's all!

If class loaded using composer's autoload mechanism - 
`class_exists($class)` returns true.

if method_exists in class - it will return true.

Now you can call class->method with given variables

**Comment by peter279k** [comment]
The current package requires path setting and the router know about controllers and middlewares.

If letting this package knows the namespace from `autoload` block on `composer.json`, it should change some behaviors about detecting controller and middleware namespaces.

**Comment by peter279k** [comment]
@KarelWintersky, could you have any sample project/repository about this issue you mention?

I want to try reproducing this issue by myself.

Thanks :).

**Comment by cowretwc** [comment]
@KarelWintersky I found a solution , because i have same problems to , i use psr-4 and i can call my class and just show "class is not found. Please, check file.".

so , to fix this you just need to change some code on Router.php to this :

`public function __construct(array $params = [])
    {
        #$this->documentRoot = realpath($_SERVER['DOCUMENT_ROOT']);
        #$this->runningPath = realpath(getcwd());
        #$this->baseFolder = $this->runningPath;

        if (isset($params['debug']) && is_bool($params['debug'])) {
            RouterException::$debug = $params['debug'];
        }
        $this->setPaths($params);
        $this->loadCache();
    }`

**Comment by KarelWintersky** [comment]
@cowretwc , I wrote my own router, based on nikic/fast-router. See my profile, repo Arris, class AppRouter.
