### ISSUE TITLE
Enhance tests environment on Travis CI build

### ISSUE THREAD

**Issue by peter279k** [izniburak/php-router#20]
To let Travis CI build environment be similar with production environment, I plan to drop PHP built-in web server. And using the `Apache+PHP` environment instead.

@izniburak, once this issue is accepted, I will work on this.

**Comment by izniburak** [comment]
Hi @peter279k , this is great! It will be good. I think we can do it.

**Comment by peter279k** [comment]
Closed via PR #21.
