### ISSUE TITLE
get var 

### ISSUE THREAD

**Issue by NeftaliAcosta** [izniburak/php-router#23]
I need to get the identifier of an object through the get method. For example:

```
$this->route->get('/item/{item}', function() {
 some code here
});
```

This is possible?

Thank you.

**Comment by izniburak** [comment]
Hi @NeftaliAcosta ,
I couldn't understand your question clearly. What is your problem exactly?

**Comment by NeftaliAcosta** [comment]
Thanks for your answer. I already found what I needed:
https://github.com/izniburak/php-router/wiki/4.-Parameter-Patterns


However, I still have a problem. I just need to validate an error page (for example 404), in case no route has been found. I have a template for this message and I want to use in case any route does not exist.

Thanks

**Comment by peter279k** [comment]
Yes. It seems that you find the new missing feature about customized error
page.

@izniburak, you need to consider this issue.

Neftalí Acosta <notifications@github.com> 於 2020年2月2日 週日 上午8:59 寫道：

**Comment by izniburak** [comment]
Hi,
Actually, you can do it! I will also add this to documentation. Try this:
```php 
$router->error(function() {
    // your error view (for no route - 404)
});
```
Currently, the **error** method only accepts `function` parameter.

**Comment by peter279k** [comment]
Yes. I see :), thanks for @izniburak explanation and help.

**Comment by NeftaliAcosta** [comment]
> Hi,
> Actually, you can do it! I will also add this to documentation. Try this:
> 
> ```
> $router->error(function() {
>     // your error view (for no route - 404)
> });
> ```
> 
> Currently, the **error** method only accepts `function` parameter.

Thank you <3
