### ISSUE TITLE
Add customized error section on GitHub Wiki

### ISSUE THREAD

**Issue by peter279k** [izniburak/php-router#24]
As the issue #23 mentions about how to customized error page view.

It's possible, but there are no guide to tell developers how to do it.

That is, it misses on GitHub Wiki. And it seems that this should have new section name is like "customized error page" on GitHub Wiki.

However, I would be happy with working on this, but I have no permission to edit GitHub Wiki :).

I just create new issue to mention and track :smile:.

**Comment by izniburak** [comment]
Wiki page has been completed for that.  [Check out it.](https://github.com/izniburak/php-router/wiki/8.-Custom-Error-(404))
