### ISSUE TITLE
how can we get request body in post request?

### ISSUE THREAD

**Issue by AftabFalak** [izniburak/php-router#25]
kindly update the documentation. there is no guidance of how to use post request

**Comment by izniburak** [comment]
Hi @AftabFalak ,
Actually, there is a documentation about that. You can check [this link](https://github.com/izniburak/php-router/wiki/3.-Methods).
Thanks.

**Comment by AftabFalak** [comment]
okay thanks and how can I get data via a put, delete requests

**Comment by izniburak** [comment]
Hi,
You can check this [documentation](https://www.php.net/manual/en/features.file-upload.put-method.php). Also, you can use a helper class that can access and manage HTTP request and response datas like [Symfony HTTP Foundation](https://github.com/symfony/http-foundation). 

BTW, I'm planning to develop some helper function that will be able to used in this package about Request/Response. I hope that i would complete that asap.
