### ISSUE TITLE
Problem setting up under a different file path (not project root)

### ISSUE THREAD

**Issue by Novocaine88** [izniburak/php-router#26]
Set up
-

On an existing website, I want to add an `/api` routing path. The current website does not have any prepackaged routing, and utilises a CMS for standard pages.

The API route is new and I want to create a routing system similar to Laravel without the overhead of a Framework.

Attempts
-

My basic set up looks like this, however I'm running into issues;

```php
$router = new Buki\Router();


$router->get('/api', function() {
    return 'Hello World';
});

$router->get('/api/user', function() {
    return 'Hello World 2';
});
```

My rough folder structure looks like so, where all requests are routed towards index.php and this file requires routes.php if the path matches `'/^\/api\/?(.*)/'`. `/public` is configured as the root of the website in the htconfig

```
/var/www/{site name}/public/index.php
/var/www/{site name}/public/tpl/core/api
|-- routes.php
|-- \vendor
```

The php above works on the `/api` url, however it receives a 404 (from the package `<h2>Opps! An error occurred.</h2> Route not found. Looks like something went wrong. Please try again.`) on `/` or `/api/user` paths or any of my other tests based of the `/api/...` path

I can log out the `$router` variable (`error_log(print_r([$router], true));`) under either url and successfully see that the package is running and does show the 2 routes I'm testing with, but throws only a 404 not found on anything other than `/api`.

The package does say that I can edit the base folder using
```php
$router = new Buki\Router([
    'base_folder' => '/api',
]);
```

for instance, but this doesn't seem to work.
I don't think this is necessarily an issue with the package, as I've tried about 4 other PHP packages claiming to do the same, and they all correctly register the routes I've set, they just don't seem to match any and show none of the output.

**Comment by jmmolina796** [comment]
I have the same issue. I tried this code, but it is not working:

```
$router->group('admin', function($r) {
        $r->get('foo', function(){ echo 'page: admin/foo'; });
        $r->get('bar', function(){ echo 'page: admin/bar'; });
        $r->get('baz/php', function(){ echo 'page: admin/baz/php'; });
        $r->post('login', function(){ echo 'page: admin/login'; });
});
```

I receive a 404 when I enter this routes:

```
- GET /admin/foo
- GET /admin/bar
- GET /admin/baz/php
- POST /admin/login
```

**Comment by izniburak** [comment]
Hi @Novocaine88 and @jmmolina796 ;
Did you configure webserver config file? (like .htaccess)
You can check [this documentation](https://github.com/izniburak/php-router/wiki/2.-Getting-Started#quick-usage).

**Comment by jmmolina796** [comment]
Yes, I have configured .htaccess. Everything is working except nested routes. I'm using php 7.4 with Docker.

**Comment by izniburak** [comment]
Where is the .htaccess file? 
Actually, I just tried to test this problem by using it in subfolder and I didn't see any problem. It seems working with subfolder. 
I'm not sure your webserver configuration and router config if it's true.
Can you share this information with its path?

**Comment by Novocaine88** [comment]
Hi @izniburak 

So my folder set up for all relevant files looks like this
```
/var/www/{site name}/public
| -- .htaccess
| -- index.php
| -- /tpl/core/api
| -- | -- routes.php
| -- | -- /vendor
```

My .htaccess file has the following to route everything to the `/public/index.php` file.
```apache
RewriteCond %{REQUEST_FILENAME} !-f
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_URI} !=/favicon.ico
RewriteRule ^ index.php [L]
```

My index.php file contains this, to then include the `/public/tpl/core/api/routes.php` file
```php
if (preg_match('/^\/api\/?(.*)/', $route->uri, $api_path)) {

    require_once(PHP_ROOT . '/core/api/routes.php');
    exit();
}
```

And finally the `/public/tpl/core/api/routes.php` file, has the code from my first post;
```php
$router = new Buki\Router();


$router->get('/api', function() {
    return 'Hello World';
});

$router->get('/api/user', function() {
    return 'Hello World 2';
});
```


Do you have an example project _with_ this in a subfolder you could share? Maybe I can take that and figure out what I've not done right.

**Comment by izniburak** [comment]
Hi @Novocaine88 ,
I attached a file for testing router with directory structure that is similar to yours.
You can check it. 
I think the problem is about your codes. Please check these:
- Include autoload files
- Trigger `run` method in Router after your route definition.

[router-test.zip](https://github.com/izniburak/php-router/files/4570874/router-test.zip)

Thanks.
