### ISSUE TITLE
Instagram gibi URL yapısını nasıl yapabilirim?

### ISSUE THREAD

**Issue by burakalac4** [izniburak/php-router#28]
`$router->get('/:any', 'mainController@main');`
bu şekilde yaptım
```
public function main($ad)
{
	if($ad == "")
      {
		return 'Main method';
	}
	else
	{
		return 'Main method: ' . $ad ;
	}

}
```
Controller kısmını bu şekilde yaptım /burak olarak girince çıktıyı şu şekilde alabiliyorum
`Main method: burak`
fakat / bu şekilde girince sayfayı bulunamadı hatası veriyor nasıl yapabilirim yardımcı olur musunuz?

**Comment by darkwe** [comment]
Sorun çözüldü şu şekilde yaptım.
```
$router->get('/', 'mainController@main');
$router->get('/:any', 'mainController@ad');
public function main()
{

	return 'Main method';

}
public function ad($ad)
{
	return 'Main method: ' . $ad ;

}
```

**Comment by izniburak** [comment]
Merhaba @darkwe ,
Eğer `optional` parametre kullanmak istiyorsanız, pattern sonuna `?` ekleyebilirsiniz. Örnek olarak şu şekilde yapabilirsiniz:

```php 
$router->get('/:any?', 'MainController@yourMethod');

// MainController -> yourMethod
public function yourMethod($param = null)
{
    // your logic
}
```

**Comment by darkwe** [comment]
Auto-generated Routes'ta 
/bar ve /bar/:any olarak nasıl yapabilirim? 
```
	public function main()
	{
		return 'main yok';
	}
	public function main($id)
	{
		return 'main var : ' . $id;
	}
```
Bu şekilde hata veriyor mükerrer olduğu için @izniburak 
Teşekkürler güzel simple bir sistem

**Comment by izniburak** [comment]
Auto-generated Route'lar için siz bir method içerisinde parametreye default değer verirseniz, otomatik olarak yukarda belirttiğim halde tanımlar. Router bunu kendi algılayabiliyor. Değeri olmayan parametreler require, diğerleri optional oluyor.
