### ISSUE TITLE
router match

### ISSUE THREAD

**Issue by TheYkk** [izniburak/php-router#3]
mesela ben sadece get ve post metgodunda calisan router yapcam ama oyle bir secenegimiz yok
sadece any ve get veya post var nasil yapabiliriz
http://prntscr.com/jjob0a

**Comment by izniburak** [comment]
Merhabalar @TheYkk ,
Şu şekilde deneme yapabilirsin;
```php
$router->add('GET|POST', '/test', function()
{
  echo "Hello World. I'm working GET or POST method.";
});
```
