### ISSUE TITLE
Xammp Localhost'ta sorun yok FTP'de sorun var sayfa bulunamıyor

### ISSUE THREAD

**Issue by burakalac4** [izniburak/php-router#30]
Merhaba @izniburak Hocam;

`$router = new Buki\Router();`
Bu şekilde çağırmaktayım

Bu şekilde 3 farklı şekilde denememe rağmen olumsuz, sayfa bulunamadı diyor.
1.
```
$router->get('/kredi/yukle', function() {
	oturumy();
	global $db;
	echo "var";
	// include 'library/view/addbalance.php';
});
```
2.
```
$router->post('/kredi/yukle', function() {
	oturumy();
	global $db;
	echo "var";
	// include 'library/view/addbalance.php';
});
```
3.
```
$router->add('GET|POST|AJAX', '/kredi/yukle', function() {
	oturumy();
	global $db;
	echo "var";
	// include 'library/view/addbalance.php';
});
```
.htaccess dosyası
```
RewriteEngine On
RewriteCond %{REQUEST_FILENAME} !-d
RewriteCond %{REQUEST_FILENAME} !-f
RewriteRule ^ index.php [L]
```

**Comment by izniburak** [comment]
Merhaba,
Directory Structure'ı nasıl yaptınız? Server da uygulamayı çalıştırdığınız path nedir?
Wiki sayfasından detaylı olarak konfigurasyonlar kısmını okumanızı öneririm.

Kolay gelsin.

**Comment by burakalac4** [comment]
> Directory Structure'ı nasıl yaptınız? Server da uygulamayı çalıştırdığınız path nedir?
`
Bu kısmı tam anlıyamadım 
Wiki kısmını okmuşumtum hocam localhost'ta sorun yoktu dediğim gibi host'a aktarınca bazı rotaları görmüyor bazılarında sorun yok.

**Comment by izniburak** [comment]
Oluşturduğunuz yapı ile alakalı olabilir. 
İncelemeden bir şey demek güç maalesef.

**Comment by burakalac4** [comment]
> Oluşturduğunuz yapı ile alakalı olabilir.
> İncelemeden bir şey demek güç maalesef.

PHP Versiyonu 7.4 kontrol ettim, cpanel'den belli özellikleri açmak gerekiyor mu? Sizinle iletişime geçip yapıyı göstersem yardımcı olabilir misiniz?

**Comment by izniburak** [comment]
Detayları mail olarak gönderirseniz, uygun bir vakitte bakmaya çalışırım. Dokümanlar aslında her şeyi açıklıyor, ordaki yönergeleri uyguladığınızda sorun olmaması gerekiyor. Gözden kaçan bir şeyler var gibi ama, dediğim gibi mail atarsanız, inceleyebilirim.

Kolay gelsin.

**Comment by burakalac4** [comment]
Mail adresinizden illetim, gönderdiğim mail adresi: info@burakdemirtas.org şimdiden teşekkürler.
