### ISSUE TITLE
routes don't work

### ISSUE THREAD

**Issue by NeftaliAcosta** [izniburak/php-router#31]
I have the following directory tree:

project
├── app
│   ├── controllers
│   │   └── routeControllers.php
│   ├── models
│   ├── templates
│   │   └── homeTemplate.php
│   ├── pages
│   │   ├── home.php
│   │   ├── about.php
│   │   └── contact.php
├── include
│   │   ├── system.php
├── resources
├── vendor
 ── index.php

1.- index.php includes system.php
2.- system.php loads the libraries and calls the system controller.
```
<?php

	/**
	 * Requiere los controladores y librerias
	 */
	require_once __DIR__.'/../app/auto_loader.php';
	/**
	 * Requiere las librerias de composer
	 */
	require_once __DIR__.'/../vendor/autoload.php';

	require_once 'config.php';
	Use App\Controllers\route;
	$init = new route();
	$init->pages();
```

3.- The system controller instantiates the route controller e requires the main template:
```
<?php 

	namespace  App\Controllers;

	use App\Controllers\Route;


	class route{
		private $route;

		public function __construct(){
			$this->route =  new \Buki\Router();
	    }

		public function pages(){

			/**
			 * Rutas predeterminadas del sistema
			 */
			$this->route->get('/', function() {
			   echo "home";
			});

			$this->route->get('/hola/{s}', function($value) {
			    echo "error".$value;
			});

			$this->route->error(function() {
			    echo "error";
			});


			$this->route->run();
		}
	}
```

4.- when accessing the path / hello / world the url is not detected by the controller

![image](https://user-images.githubusercontent.com/15948880/84697204-598eed80-af13-11ea-9375-03df13beca32.png)

**Edit:**
if I use the following structure it works without problem:
```
$this->route->get('/hello/:string', function($value){
  echo 'Hello, ' . $value;
});
```

**Comment by izniburak** [comment]
Hi @NeftaliAcosta ,
Probably, this problem related with base_path.
What is your base_path? You can try to change Router config. You can check out documentation.

Thanks.

**Comment by NeftaliAcosta** [comment]
> Hi @NeftaliAcosta ,
> Probably, this problem related with base_path.
> What is your base_path? You can try to change Router config. You can check out documentation.
> 
> Thanks.

It only works like this:

$this->route->get('/hello/:string', function($value){
  echo 'Hello, ' . $value;
});

**Comment by izniburak** [comment]
Everything seems normal. I couldn't understand the issue. Maybe it can be debugged for finding the problem. Did you share your project as public anywhere? Maybe, I can investigate it at a convenient time.

**Comment by NeftaliAcosta** [comment]
> Everything seems normal. I couldn't understand the issue. Maybe it can be debugged for finding the problem. Did you share your project as public anywhere? Maybe, I can investigate it at a convenient time.

I created an example of the project so you can download it.
https://github.com/NeftaliAcosta/proyecto.com.mx

The file in question is:
proyecto.com/app/routes/oferta_route.php

Thanks for your time and your help.

**Comment by NeftaliAcosta** [comment]
I've already tried many things and can't get it to work :(

**Comment by NeftaliAcosta** [comment]
@izniburak I tell you the following:
I have a project that I did 3 months ago, I copied and pasted the entire vendor / izniburak folder in my new project and now the routes already work using:

{a} => All chars without '/' char.
{d} => Digits.
{i} => Digits.
{s} => Alphabetic characters.
{w} => Alphanumeric characters.
{u} => URL format characters for SEO. (Alphanumeric characters, _ and -)
{*} => All characters

I think it is a problem of some update.

**Comment by izniburak** [comment]
@NeftaliAcosta Which version you used? Maybe we can compare it with latest version. But, I don't think that the problem is related with patterns.

**Comment by NeftaliAcosta** [comment]
Thats what I refer. I have upgraded from version 1 to 1.5 and the error occurs again.

![image](https://user-images.githubusercontent.com/15948880/88095960-8a3df480-cb5b-11ea-987e-74ef3ecc9bbf.png)


![image](https://user-images.githubusercontent.com/15948880/88095739-303d2f00-cb5b-11ea-8d4f-28ee6fef2b80.png)

```
$this->route->pattern('{key}', '[a-z0-9]+'); 
$this->route->get('oferta/{key}/{u}', function($key, $nombre) {
       include_once __DIR__.'/../views/ofertas/ver-oferta.php';
});
```



But if I change the "keys" for the double points it works magically.

```
$this->route->pattern(':key', '[a-z0-9]+'); 
$this->route->get('oferta/:key/:slug', function($key, $nombre) {
        include_once __DIR__.'/../views/ofertas/ver-oferta.php';
});

```

![image](https://user-images.githubusercontent.com/15948880/88096462-4ac3d800-cb5c-11ea-9ed0-e2c893b27f22.png)

I highly doubt it is a server problem, or maybe a configuration problem but the documentation doesn't specify what I have to do to get it to work with {}.

Thank you.
