### ISSUE TITLE
url with subfolder not working

### ISSUE THREAD

**Issue by NeftaliAcosta** [izniburak/php-router#33]
I am migrating my project to my server in production and I have a problem that I cannot detect.

Urls that have a subfolder do not work. For example

```
$this->route->get('/hello/word', function() {
 //code
});
```

but if it works:
```
$this->route->get('/hello', function() {
 //code
});
```

in the instance I have nothing special
`$this->route =  new \Buki\Router();`

I share my php info if necessary.
http://18.236.228.15/phpinfo.php

this url doesn't work
http://18.236.228.15/oferta/bbc881542d2842dcc7d0b3003411c38c/director-o-directora-comercial-en-maquinas-de-bebidas-region-centro-en-cdmx

I use:

```
$this->route->pattern(':key', '[a-z0-9]+');
$this->route->pattern(':oferta', '[a-z0-9.-]+'); 

$this->route->get('oferta/:key/:oferta', function($key, $nombre) {
	include_once __DIRTEMPLATE__.'template.php';
});
```

Thanks for your answer.

**Comment by peter279k** [comment]
Sorry. I run your PHP codes and it's worked successfully.

Here are my code snippets:

```PHP
<?php

require 'path/to/vendor/autoload.php';

use Buki\Router;

$router = new Router();

$router->pattern(':key', '[a-z0-9]+');
$router->pattern(':oferta', '[a-z0-9.-]+');

$router->get('oferta/:key/:oferta', function($key, $nombre) {
    return 'key, oferta route with custom patterns';
});

$router->run();
```

**Comment by NeftaliAcosta** [comment]
Do you think it is a php or my server configuration problem?
On localhost if it works, it is probably that, but I don't know what the technical requirements of the plugin are.


I can share you SFTP access if necessary. :/

**Comment by NeftaliAcosta** [comment]
> Sorry. I run your PHP codes and it's worked successfully.
> 
> Here are my code snippets:
> 
> ```
> <?php
> 
> require 'path/to/vendor/autoload.php';
> 
> use Buki\Router;
> 
> $router = new Router();
> 
> $router->pattern(':key', '[a-z0-9]+');
> $router->pattern(':oferta', '[a-z0-9.-]+');
> 
> $router->get('oferta/:key/:oferta', function($key, $nombre) {
>     return 'key, oferta route with custom patterns';
> });
> 
> $router->run();
> ```

Do you think it is a php or my server configuration problem?
On localhost if it works, it is probably that, but I don't know what the technical requirements of the plugin are.

I can share you SFTP access if necessary. :/

**Comment by peter279k** [comment]
Maybe it's your sever configuration problem and you should add `.htaccess` on your project root folder.

If you want to share SFTP access to me, please email me, thanks :).

**Comment by NeftaliAcosta** [comment]
> Maybe it's your sever configuration problem and you should add `.htaccess` on your project root folder.
> 
> If you want to share SFTP access to me, please email me, thanks :).

I Activate debugger mode
vendor\izniburak\router\src\Router\RouterException.php

And the exception is telling me that there is a problem with the $ uri of the Router.php file. Process to remove this part of the code from this file.

```
if ($_SERVER['REQUEST_URI'] !== $_SERVER['PHP_SELF']) {
            $uri = str_replace(dirname($_SERVER['PHP_SELF']), '', $uri);
        }
        
        if (($base !== $uri) && (substr($uri, -1) === '/')) {
            $uri = substr($uri, 0, (strlen($uri) - 1));
        }
```



And magically my urls work:

http://18.236.228.15/oferta/f0e58fe2a606a5c86aa33cd101b01b70/disenador-grafico-ui-en-cdmx
![image](https://user-images.githubusercontent.com/15948880/91005209-eef5d000-e59b-11ea-894f-5d903f26e2e4.png)


Now the problem is that when removing those lines the middleware doesn't work. :(
![image](https://user-images.githubusercontent.com/15948880/91005447-88bd7d00-e59c-11ea-9ca0-fb20c74904d6.png)

T_T  (I'm crying)

**Comment by peter279k** [comment]
Here is my router configuration:

```PHP

$params = [
    'paths' => [
        'controllers' => 'controllers/',
    ],
    'namespaces' => [
        'controllers' => 'Controllers\\',
    ],
    'base_folder' => __DIR__,
    'main_method' => 'main',
];

$router = new Router($params);

```

I have no middleware to use on this application.

**Comment by izniburak** [comment]
@NeftaliAcosta , Do you still have any problem about that?

**Comment by NeftaliAcosta** [comment]
> Do you still have any problem about that?

Hi, Thanks for your time. Yes, all the Middleware routes still do not work for me, I keep testing my site.

Is it normal that I have to comment on this part of the code for the plugin to work on my site in Router.php?

```
 /**
     * Run Routes
     *
     * @return void
     * @throws
     */ 
    public function run()
    {
        $base = str_replace('\\', '/', str_replace($this->documentRoot, '', $this->runningPath));
        $uri = rtrim(parse_url($_SERVER['REQUEST_URI'], PHP_URL_PATH), '/');
        /*
        if ($_SERVER['REQUEST_URI'] !== $_SERVER['PHP_SELF']) {
            $uri = str_replace(dirname($_SERVER['PHP_SELF']), '', $uri);
        }

        if (($base !== $uri) && (substr($uri, -1) === '/')) {
            $uri = substr($uri, 0, (strlen($uri) - 1));
        }
        */
}
```

**Comment by izniburak** [comment]
Could you share $_SERVER variable values by using var_dump or something else?
We should debug that problem on your side because i couldn't reproduce the problem on my side. (local and prod)

**Comment by NeftaliAcosta** [comment]
> Could you share $_SERVER variable values by using var_dump or something else?
> We should debug that problem on your side because i couldn't reproduce the problem on my side. (local and prod)

I made var_dump () on home

`array(31) { ["HTTP_HOST"]=> string(13) "18.236.228.15" ["HTTP_CONNECTION"]=> string(10) "keep-alive" ["HTTP_DNT"]=> string(1) "1" ["HTTP_UPGRADE_INSECURE_REQUESTS"]=> string(1) "1" ["HTTP_USER_AGENT"]=> string(131) "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36 Edg/84.0.522.63" ["HTTP_ACCEPT"]=> string(124) "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" ["HTTP_ACCEPT_ENCODING"]=> string(13) "gzip, deflate" ["HTTP_ACCEPT_LANGUAGE"]=> string(92) "es-ES,es;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,ca;q=0.5,da;q=0.4,pt;q=0.3,tr;q=0.2,uk;q=0.1" ["PATH"]=> string(29) "/sbin:/usr/sbin:/bin:/usr/bin" ["SERVER_SIGNATURE"]=> string(0) "" ["SERVER_SOFTWARE"]=> string(33) "Apache/2.4.43 (Amazon) PHP/7.2.31" ["SERVER_NAME"]=> string(13) "18.236.228.15" ["SERVER_ADDR"]=> string(12) "172.31.12.15" ["SERVER_PORT"]=> string(2) "80" ["REMOTE_ADDR"]=> string(15) "201.111.251.160" ["DOCUMENT_ROOT"]=> string(29) "/var/www/vhost/jobtify.com.mx" ["REQUEST_SCHEME"]=> string(4) "http" ["CONTEXT_PREFIX"]=> string(0) "" ["CONTEXT_DOCUMENT_ROOT"]=> string(29) "/var/www/vhost/jobtify.com.mx" ["SERVER_ADMIN"]=> string(14) "root@localhost" ["SCRIPT_FILENAME"]=> string(39) "/var/www/vhost/jobtify.com.mx/index.php" ["REMOTE_PORT"]=> string(5) "51278" ["GATEWAY_INTERFACE"]=> string(7) "CGI/1.1" ["SERVER_PROTOCOL"]=> string(8) "HTTP/1.1" ["REQUEST_METHOD"]=> string(3) "GET" ["QUERY_STRING"]=> string(0) "" ["REQUEST_URI"]=> string(1) "/" ["SCRIPT_NAME"]=> string(10) "/index.php" ["PHP_SELF"]=> string(10) "/index.php" ["REQUEST_TIME_FLOAT"]=> float(1598250454.43) ["REQUEST_TIME"]=> int(1598250454) }`




I am also using a subdomain:
`array(33) { ["HTTP_HOST"]=> string(19) "test.jobtify.com.mx" ["HTTP_CONNECTION"]=> string(10) "keep-alive" ["HTTP_DNT"]=> string(1) "1" ["HTTP_UPGRADE_INSECURE_REQUESTS"]=> string(1) "1" ["HTTP_USER_AGENT"]=> string(131) "Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/84.0.4147.135 Safari/537.36 Edg/84.0.522.63" ["HTTP_ACCEPT"]=> string(124) "text/html,application/xhtml+xml,application/xml;q=0.9,image/webp,image/apng,*/*;q=0.8,application/signed-exchange;v=b3;q=0.9" ["HTTP_REFERER"]=> string(44) "http://test.jobtify.com.mx/ofertas-recientes" ["HTTP_ACCEPT_ENCODING"]=> string(13) "gzip, deflate" ["HTTP_ACCEPT_LANGUAGE"]=> string(92) "es-ES,es;q=0.9,en;q=0.8,en-GB;q=0.7,en-US;q=0.6,ca;q=0.5,da;q=0.4,pt;q=0.3,tr;q=0.2,uk;q=0.1" ["HTTP_COOKIE"]=> string(114) "PHPSESSID=hfjh047lr0cjd20lv0bar4li9a; __gads=ID=bc96836bc33c940e:T=1598249651:S=ALNI_Maafdiu2nAXZpS9vQIBK5Euz8BIIA" ["PATH"]=> string(29) "/sbin:/usr/sbin:/bin:/usr/bin" ["SERVER_SIGNATURE"]=> string(0) "" ["SERVER_SOFTWARE"]=> string(33) "Apache/2.4.43 (Amazon) PHP/7.2.31" ["SERVER_NAME"]=> string(19) "test.jobtify.com.mx" ["SERVER_ADDR"]=> string(12) "172.31.12.15" ["SERVER_PORT"]=> string(2) "80" ["REMOTE_ADDR"]=> string(15) "201.111.251.160" ["DOCUMENT_ROOT"]=> string(29) "/var/www/vhost/jobtify.com.mx" ["REQUEST_SCHEME"]=> string(4) "http" ["CONTEXT_PREFIX"]=> string(0) "" ["CONTEXT_DOCUMENT_ROOT"]=> string(29) "/var/www/vhost/jobtify.com.mx" ["SERVER_ADMIN"]=> string(14) "root@localhost" ["SCRIPT_FILENAME"]=> string(39) "/var/www/vhost/jobtify.com.mx/index.php" ["REMOTE_PORT"]=> string(5) "51289" ["GATEWAY_INTERFACE"]=> string(7) "CGI/1.1" ["SERVER_PROTOCOL"]=> string(8) "HTTP/1.1" ["REQUEST_METHOD"]=> string(3) "GET" ["QUERY_STRING"]=> string(0) "" ["REQUEST_URI"]=> string(1) "/" ["SCRIPT_NAME"]=> string(10) "/index.php" ["PHP_SELF"]=> string(10) "/index.php" ["REQUEST_TIME_FLOAT"]=> float(1598250499.974) ["REQUEST_TIME"]=> int(1598250499) }`
