### ISSUE TITLE
router not find my url

### ISSUE THREAD

**Issue by maganius** [izniburak/php-router#38]
This is my router config.

```PHP
use Buki\Router;
$router = new Router([
    'debug' => true,
    'base_folder' => __DIR__,
    'paths' => [
        'controllers' => 'Controllers',
    ],
    'namespaces' => [
        'controllers' => 'App\Controller',
    ],
]);

$router->get('/', 'Controller@home');
$router->get('/get/:user_code', 'Controller@getUser');
$router->run();
```

Home route work correctly but `/get/:user_code` doesnt works. Router says:
Uncaught Exception: Route not found.

I dump result of preg_math at `Router.php@433`

` var_dump(preg_match('#^' . $route . '$#', $uri, $matched), $route, $uri);`

with this result:

`int(0) string(19) "/get/:user_code" string(14) "/getdsadsa"`

I think the uri should be `/get/dsadsa`?

**Comment by izniburak** [comment]
Hi @maganius , 
Did you define a new pattern for `:user_code`?
Could you please check [available parameters](https://github.com/izniburak/php-router/wiki/4.-Parameter-Patterns)?
Thanks.
