### ISSUE TITLE
Can I get a variable from route in middleware?

### ISSUE THREAD

**Issue by NeftaliAcosta** [izniburak/php-router#39]
I have the following route with its respective middleware working:

```
	$this->route->pattern(':key', '[a-z0-9]+');
	$this->route->get('/url/path/:key', ['before' => 'thisMiddleware'],function($key) {
		//Code
	});
```

```
<?php 

namespace App\Middlewares;

use App\Controllers\sessionController,
App\Controllers\loginController,
App\Controllers\usuarioController,
App\Controllers\tools;

class thisMiddlewareMiddleware{

	public function handle(){
		echo $key;
	}

}
```

I need to access the "key" variable that is being obtained in the route in order to decide what to do

Tried doing the following but it arrives empty.

This is possible?
Thank you.
```
$this->route->get('/url/path/:key', ['before' => 'thisMiddleware::handle($key)'],function($key) {
		//Code
});

public function handle($key){
	echo $key;
}
```

**Comment by izniburak** [comment]
Hi, 
For v1.x, you can not access to the `$key` variable in Middleware directly. But I prepared a new version as v2.0 in this week. It has been released. I didn't update documentation for the new version, but I will as soon as possible. 

Now, the Router is more flexible and strong. I added a few new feature into the library. You can check project files or wait the documentation for updates.

Thanks.

**Comment by NeftaliAcosta** [comment]
> Hi,
> For v1.x, you can not access to the `$key` variable in Middleware directly. But I prepared a new version as v2.0 in this week. It has been released. I didn't update documentation for the new version, but I will as soon as possible.
> 
> Now, the Router is more flexible and strong. I added a few new feature into the library. You can check project files or wait the documentation for updates.
> 
> Thanks.

Great! thank you, check it immediately.

**Comment by federicocandiago** [comment]
Hello, 
I read [the updated docs](https://github.com/izniburak/php-router/wiki/6.-Middlewares), but unfortunately it's still not clear to me how to use a routing variable inside the middleware. for instance, in this case:
```$router->post('/app/:id/login', 'Api.LoginController@login', ['before' => 'ValidationMiddleware']);```
I'm looking to evaluate the $id variable inside the middleware. Probably it's me getting it wrong.. could you please help me\us on this case?

Thanks again for the amazing work!

**Comment by izniburak** [comment]
Thank you for your comment. I've planned the implementation and I'm working on that.
