### ISSUE TITLE
404 icin wiki yok

### ISSUE THREAD

**Issue by TheYkk** [izniburak/php-router#4]
custom 404 icin wiki yok

**Comment by izniburak** [comment]
Merhaba @TheYkk , dokümantasyonu tamamlamaya çalışıyorum ama son zamanlarda oldukça yoğun olduğum için fazla fırsatım olmuyor. Yine de en kısa zamanda tamamlamak, önceliklerim arasında. 

Basitçe şu şekilde deneme yapabilirsin;
```php
# Error
$router->error(function()
{
  echo 'Error!';
});
```
