### ISSUE TITLE
PHP 8 getClass method is deprecated 

### ISSUE THREAD

**Issue by nabeelalihashmi** [izniburak/php-router#40]
Filename: src/RouterCommand.php

line near ~280 

// $class = $param->getClass();

Fix: 
use ReflectionClass;

$class = $param->getType() && !$param->getType()->isBuiltin()
                ? new ReflectionClass($param->getType()->getName())
                : null;

**Comment by izniburak** [comment]
Hi @nabeelalihashmi ,
Thank you for your feedback and solution. I will try to test it and publish a new release for the Router ASAP.

**Comment by izniburak** [comment]
Hi,
This issue has been fixed with the new version. (v2.3.0)
You can update your package via composer or manually.

Thanks.

**Comment by nabeelalihashmi** [comment]
Awesome!!!!
