### ISSUE TITLE
middleware  in group whith version 2

### ISSUE THREAD

**Issue by NeftaliAcosta** [izniburak/php-router#41]
I try creating a middleware in the new version, but I have some errors, I try to do it as it did  in version 1.0:

> <?php 
	$this->route->group('/panel', 'IndexController@main',['before' => 'sessionMiddleware'],  function($r){
           some code		
	});

![A test image](https://i.ibb.co/3TPFL7g/route.png)

**Comment by izniburak** [comment]
Hi,

Please try like that:
```php 
$this->route->group('/panel', function($r) {
       some code		
}, ['before' => 'sessionMiddleware']);
```

in version 2, changed some usage. Please check documentation.
