### ISSUE TITLE
What template manager for PHP do you recommend? 

### ISSUE THREAD

**Issue by NeftaliAcosta** [izniburak/php-router#42]
Hi guys, I am creating a professional project with your plugin (when I have it obviously I will give you the credits), I like it a lot for its simplicity and practicality.

I want to take the project to a more professional level. Can you recommend a template manager that will help me incorporate it with your plug-in and work without problem?

Thanks for the recommendation. Greetings.

**Comment by izniburak** [comment]
Hi @NeftaliAcosta ,
I guess you want to a template engine recommendation, right? If it is, I usually use Blade template engine in my projects. I have no problem for it with the Router. If you make right implementation, I think, whatever template engine you use, it doesn't matter.

**Comment by peter279k** [comment]
There are some PHP templates I recommend:

- Native PHP template. (It should prevent XSS by yourself)
- [Twig without Symfony](https://zetcode.com/php/twig/).
- [Blade without Laravel framework](https://github.com/jenssegers/blade).

**Comment by NeftaliAcosta** [comment]
thanks guys

**Comment by nfn** [comment]
Hi, any example of how can I integrate with Blade ow Twing? Thanks

**Comment by izniburak** [comment]
Hi @nfn, 
Template engine usage is such a different concept from PHP Router. But, yes. You can use them. For example; you can add Blade or Twig to your project and create a new instance with one of the these packages. Then, you can use it in the router handler. There is no any problem or restrict for that.
