### ISSUE TITLE
Typo in the wiki

### ISSUE THREAD

**Issue by ozgurg** [izniburak/php-router#43]
I found a typo in the Controllers wiki.

There is a missing `"` in "Auto-generated Routes" code example.
https://github.com/izniburak/php-router/wiki/5.-Controllers

![Screenshot_1](https://user-images.githubusercontent.com/6717356/108994221-91f2e800-76ac-11eb-8202-c7c0c84d9141.png)

**Comment by izniburak** [comment]
Thank you! I've just fixed it.
