### ISSUE TITLE
Using Routes On Terminal Commands

### ISSUE THREAD

**Issue by kivancagaogluu** [izniburak/php-router#47]
How can we use this route settings when we are running script on terminal? CodeIgniter has /path/to/index.php controller method type of usage. Do we have similiar thing in here?

**Comment by peter279k** [comment]
You can consider following steps:

- Clone this repository and using `composer install` command to install required dependencies.
- Creating the `index.php` and adding following codes:

```php
<?php

require 'vendor/autoload.php';

use Buki\Router\Router;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

$router = new Router;

// For basic GET URI
$router->get('/', function(Request $request, Response $response) {
    $response->setContent('Hello World');
    return $response;

    # OR
    # return 'Hello World!';
});

$router->run();
```

- Then running `php -S localhost:3000 index.php` to start a PHP development server.
- It will see following captured picture when opening the web browser to visit `http://localhost:3000`:

![圖片](https://user-images.githubusercontent.com/9021747/116989244-15136880-ad04-11eb-89af-772d7282e3f0.png)

**Comment by kivancagaogluu** [comment]
Hello Peter, thank you for reply but my answer is running spesific controller via terminal. On browser it works perfectly.

**Comment by peter279k** [comment]
Your question is not available for this router at this moment and I think it's the future feature :).

**Comment by izniburak** [comment]
Hi @kivancagaogluu ,
You can not access Routes on the terminal directly. Because, Router needs a web server like Apache, Nginx or PHP built-in server. There must be Request and Response for Router to use HTTP. I guess your purpose is different but I don't know that we will implement the feature like that or not. Maybe we can discuss about that  in the topic.

**Comment by kivancagaogluu** [comment]
Thanks for answers. I will try to add argv globals to route. Maybe someone want to use cronjob with php command

**Comment by peter279k** [comment]
If you want to access specific route URL with controller, I recommend you can consider using the `curl` command to make request.

And above command can be used in Cron job schedule :).

**Comment by kivancagaogluu** [comment]
Yes but there is limitations via curl and it is pretty slow compared with php shell commands. I checked Symfony http foundation and found argv arguments in createFromGlobals. I think i will solve this problem

**Comment by kivancagaogluu** [comment]
So not much but worked for me. In Router.php line 278 we can take if bash parameters exists and set uri to it. It is temporary solutions in my project but i believe you guys will create better solutions for this. Thank you for this beatifull class.

`
if($argv[1]){
            $uri = '/' . $argv[1];
        }else{
            $uri = $this->getRequestUri();
        }
`

**Comment by izniburak** [comment]
Great! Maybe we can follow that solution and add a new capability to the package!
Thanks.
