### ISSUE TITLE
Controller Bulunamadı

### ISSUE THREAD

**Issue by ahmetbarut** [izniburak/php-router#48]
Merhaba, Rota `controlleri` görmüyor 

**Dizin yapısı bu şekilde**
- app
   - Controllers
   - web.php
- config
- core
- public
- vendor

```php
$router = new Router([
    'paths' => [
        'controllers' => 'app/Controllers',
    ],
    'namespaces' => [
        'controllers' => 'App\Controllers',
    ]
]);
```

**Comment by izniburak** [comment]
Merhaba,
Kullandığınız dizin yapısına göre ayarlarınızı doğru yaptıysanız, problem olmaması lazım. Autoload'ı ve Router->run metodunu hangi dosyada tetikliyorsunuz? Buna göre `base_path` ayarınızı bakabilirsiniz Router için: https://github.com/izniburak/php-router/wiki/2.-Getting-Started#other-settings

**Comment by ahmetbarut** [comment]
@izniburak Teşekkür ederim sorunumu çözmüş bulunmaktayım
