### ISSUE TITLE
router->error ile blade sayfası çağırma

### ISSUE THREAD

**Issue by bymustfa** [izniburak/php-router#49]
router->error ile 404 işlemlerini yönetebileceğim bir blade / php sayfasına yönlendirmeye çalışıyorum sanırım bunu desteklemiyor

**Comment by izniburak** [comment]
Merhaba,
Custom errorlar için buradaki gibi bir yöntem kullanabilirsiniz:
https://github.com/izniburak/php-router/wiki/8.-Custom-Error-(404)

Router kendi içerisinde blade vs gibi template engine'leri barındırmıyor. Ama siz kendi projenizde bu tarz engine'leri kullanmak için bir implementasyon yaptıysanız, buna göre custom error metodu ile bunu kullanabiliyor olmanız gerekiyor.

**Comment by bymustfa** [comment]
Anbladım teşekkürler
