### ISSUE TITLE
ek ozellik

### ISSUE THREAD

**Issue by TheYkk** [izniburak/php-router#5]
gruplarken namespace ve middleware tanimlayabilirim

bu arada ajax seyi guzel olmus

**Comment by izniburak** [comment]
Grouplama işlemlerinde middleware ve namespace zaten tanımlanabiliyor. 
Dokümantasyonu en kısa zamanda güncelleyeceğim. 

```php
Route::group('/group', ['before' => 'Foo\\Bar\\Class@method'], function() {
  // your codes...
}
```

Route::ajax metodu kullanışlığı bir method. Aynı zamanda ajax istediğinin POST bir http isteği olmasını kontrol etmek isterseniz, Route::ajaxp metodu da bulunuyor.

Teşekkürler.

**Comment by TheYkk** [comment]
vermis oldugunuz ornek namespace icin ya middleware

**Comment by izniburak** [comment]
Verilen örnek middleware tanımlamasıydı. before ve after olarak middleware tanımlaması yapabiliyorsunuz. Namespace buralarda kullanılabiliyor fakat, genel olarak bir namespace kapsaması özelliği şu an yok.
