### ISSUE TITLE
How to attach the session to request parameter of a route?

### ISSUE THREAD

**Issue by raynaud09** [izniburak/php-router#50]
Hi,

I don't have any previous experience about Symfony or your library. I couldn't find out how to access to session inside a route with request variable. I start a session with Symfony Session class at top of my index.php file but when I call $request->getSession(), I got an "Uncaught BadMethodCallException: Session has not been set" error.

What is the right way of working with sessions inside route functions?

Thanks.

**Comment by izniburak** [comment]
Hi,
You can use [this documentation](https://symfony.com/doc/current/components/http_foundation.html) for Request and Session.
Firstly, you must create a new `Session` and `Request` object and attach `Session` to `Request`. For example:
```php
$request = new Request(/** your parameters **/);
// OR
$request = Request::createFromGlobals();

// After that create a new session object
$session = new Session();

// And attach it to Request object.
$request->setSession($session);
```
After all these operations, you must use `$request` object while creating new Router instance:
```php
$router = new Router($config, $request); // parameters: $config, $request, $response
```
I hope this would help you.

**Comment by raynaud09** [comment]
I got the main point for the solution now. 
Thanks for help and this library.
