### ISSUE TITLE
Middleware'e parametre göndermek

### ISSUE THREAD

**Issue by gereksizler2015** [izniburak/php-router#52]
Selam.
Middleware'e parametre göndermek mümkün mü? Controllerda örneğin middleware'e X göndereceğim, middleware handle fonksiyonu içinde X'in değerine göre farklı işlemler yapacağım.
https://github.com/izniburak/php-router/wiki/6.-Middlewares

**Comment by izniburak** [comment]
Merhabalar,
Direkt olarak veri aktarmanın bir yolu şu an yok. Ama `Request` instance'ını kullanıp, içerisine veri saklayabilir ve request life cycle boyunca kullanma imkanı edinebilirsiniz. Örnek olarak;

```php
// in your middleware 
public function handle(Request $request)
{
    $request->attributes->set('foo', 'bar');
    // your codes

    return true;
}
```

`before` ve `after` middleware için bu yöntemi kullanabilirsiniz. Middleware'dan controller'a data aktarmak için (beforeMiddleware) ve controller'dan Middleware'a data aktarmak için (afterMiddleware) kullanılabilir. 

Belki yeni versiyon ve upgrade çalışmaları içerisinde bu durumu ayrıca ele alıp, başka yöntemler de eklemeyi düşünebiliriz.

Kolay gelsin.
