### ISSUE TITLE
Controller için birden fazla path belirleme

### ISSUE THREAD

**Issue by Venloress** [izniburak/php-router#53]
Yönlendiriciyi bu şekilde başlatıyorum.
```
$this->router = new Router([
            'paths' => [
                'controllers' => 'App/Controllers',
                'middlewares' => 'App/middlewares'
            ],
            'namespaces' => [
                'controllers' => 'App\Controllers',
                'middlewares' => 'App\Middlewares'
            ]
        ]);
```
Controllers klasöründen başka bir yerde de controller kullanıyorum. Bunu belirtmek için en iyi çözüm nedir?
Mesela şöyle bir `App/**/Controllers` kullanımın olup olmadığını merak ediyorum.

**Comment by izniburak** [comment]
Merhabalar,

Bu tarz bir kullanım mevcut değil. `App/Controllers/**/` şeklinde kullanım yapabilirsiniz. Örneğin `Admin` dizininde oraya ait `controller` dosyaları olduğunu varsayarsak; `Admin.TestController` şeklinde kullanım yapabilirsiniz.
