### ISSUE TITLE
Url Üretme

### ISSUE THREAD

**Issue by omerfdmrl** [izniburak/php-router#56]
Merhaba. Routerda isteklerimize isim verip url üretebilir miyiz?
Örneğin;

`
$router->get('signin','Panel@signin',['before'  =>  'SigninAuth'],'app.signin.view');

$url = $router->generate('app.signin.view');
`

**Comment by izniburak** [comment]
Merhaba @omerfdmrl ,
Şu an böyle bir özellik yok ama, yakın zamanda eklemeyi düşünüyorum. Versiyon güncellemelerini takip edebilirsin.
Teşekkürler.
