### ISSUE TITLE
How to define http method type for main path in controller

### ISSUE THREAD

**Issue by ncfrv** [izniburak/php-router#61]
I'm using grouping like this:

```
$router->group('api', function($router) {
    $router->controller('book', 'BookController');
}
```
When the route
**".../api/book/"** matched,
I want to do something like this:
```
// BookController.php
public function main(){
    // if METHOD == GET : fetchAll 
        else if METHOD == POST : insert post data
}
```
Can I achieve this with defining it in controller class? Is it possible via using getMain or postMain methods?

**Comment by izniburak** [comment]
Hi @ncfrv ,
Of course. You can try to use `getMain` and `postMain` methods. Please let me know, if you still have any problem when you tried that.

Thanks.
