### ISSUE TITLE
Is there any way to serve public directory without /public/ ?

### ISSUE THREAD

**Issue by abdyek** [izniburak/php-router#62]
Hi,

I am using this library in my project. My project has front-end codes written vue-cli and back-end codes written pure PHP. I want to make it monolith it because this project is going to be like Wordpress. So users who using my project can use it easily. In other words my project is going to be ready-to-use for people.

Now, there is built front-end codes in a directory called public. How can I bypass /public/ substring in the URL? When I put built codes at root directory of my project, it run correctly. But it is not best practice.

Finally I am not sure that this problem is about routing. If it is not about routing, sorry :smile: and I am open to different ideas about my project structure.

I wish you a good coding day :man_technologist:

**Comment by izniburak** [comment]
Hi,

What's the your project structure? 

You can try such a following structure:

```
|- Controllers
|- Middewares
|- public
|----index.php
|- vendors
|- composer.json
```

According to directory structure above, you can create a file to `public/index.php` and add following lines:
```php
require __DIR__ . '/../vendor/autoload.php';

use Buki\Router\Router;

$router = new Router([
  'paths' => [
    'controllers' => __DIR__ . '/../Controllers',
    'middlewares' => __DIR__ . '/../Middlewares',
  ],
  // ... other configs
]);

// For basic GET URI
$router->get('/', function() {
    return 'Hello World!';
});

$router->run();
```

**Note:** I released a new version of the package yesterday.  Please update the package version via `composer update` command in your project when try this suggestion.

If the problem still continue, please let me know.

**Comment by abdyek** [comment]
My project structure:
```
/src/
/.. other files and directories in the root
index.php
```

I put built front end codes with index.php in /public directory and it is run correctly. It looks like more clear now. I didn't think of that before. But There is a tiny problem. Vue codes of my project uses vue-router. When I want to show a page that has some slugs, php-router redirect me the 404 page. So php-router library must leave other patterns that not defined to vue-router.

I did solve it with this codes:
```php
$router->get('/:all', function() {
    require 'index.html';
});
```

Thanks for above idea.
I wish you a good coding day :man_technologist:
