### ISSUE TITLE
v2.3.4 ile kütüphane çalışmaz oldu

### ISSUE THREAD

**Issue by ozgurg** [izniburak/php-router#63]
Merhaba.

Kütüphaneyi v2.3.0 sürümünden beri kullanıyorum. Bugün bağımlılıkları güncelledim ve bu kütüphane son güncel sürüme güncellenince çalışmamaya başladı.

Çalışmamasından kastım pathlerin çalışmaması. Tüm pathler güncelleme sonrasında 404'ü döndürmeye başladı.

Sürüm düşüre düşüre v2.3.4 ile yapılan düzenlemeden sonra çalışmadığını fark ettim. (https://github.com/izniburak/php-router/releases/tag/v2.3.4)

Composer'dan v2.3.3'e sabitleyince tekrar çalışmaya başlıyor.

Benim kodumla ilgili mi acaba veya kullanımda bir değişiklik mi olduğu diye düşündüm. Bunun üzerine README.md'deki örnek kodu Controller kısımlarını silip farklı sürümlerde çalıştırmayı denedim.

index.php
```php
<?php
require 'vendor/autoload.php';

use Buki\Router\Router;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;

$router = new Router;

// For basic GET URI
$router->get('/', function(Request $request, Response $response) {
    $response->setContent('Hello World');
    return $response;

    # OR
    # return 'Hello World!';
});

$router->run();
```

composer.json (^2.0)
```json
{
    "require": {
        "izniburak/router": "^2.0"
    }
}

```
Bu şekilde iken son sürüm olan v2.3.5'i yüklüyor ve çalışmıyor. (2.3.4'e sabitleyince de çalışmıyor) "Hello World" yazması gerekirken varsayılan 404 sayfası geliyor, "Opps! An error occurred. Looks like page not found or something went wrong. Please try again."

composer.json (2.3.3)
```json
{
    "require": {
        "izniburak/router": "2.3.3"
    }
}

```
Ancak sürümü 2.3.3'e sabitleyince çalışmaya başlıyor, "Hello World" yazıyor.

**Comment by izniburak** [comment]
Merhabalar,

Hangi sistem üzerinde çalıştırmayı deniyorsunuz? Setupınız nedir? OS, PHP sürümü, Web Server vs bilgi verebilir misiniz? Benim denemelerime göre bir problem görünmüyor ama, detaylı inceleme yapabilirim.

**Comment by ozgurg** [comment]
> Merhabalar,
> 
> Hangi sistem üzerinde çalıştırmayı deniyorsunuz? Setupınız nedir? OS, PHP sürümü, Web Server vs bilgi verebilir misiniz? Benim denemelerime göre bir problem görünmüyor ama, detaylı inceleme yapabilirim.

Tabii. Başta belirtsem daha iyi olurdu.

- Apache v2.4.52
- PHP v8.1.1
- Debian v11 (bullseye)
- Tam olarak şu Docker image'ı üzerinde çalışıyor: https://hub.docker.com/layers/php/library/php/8.1.1-apache/images/sha256-1cd55901bce2626adcc32f214f00abf3137da4abfe834cdce3155020fa6053d2

**Comment by izniburak** [comment]
Dün akşam bir güncelleme yayınladım ve bir update yaptım paket ile ilgili. 2.4.0 sürümüne yükseltmeyi deneyebilir misin?

**Comment by ozgurg** [comment]
> Dün akşam bir güncelleme yayınladım ve bir update yaptım paket ile ilgili. 2.4.0 sürümüne yükseltmeyi deneyebilir misin?

v2.4.0'a yükselttiğimde evet, subfolderda çalışmaya başladı ancak aşağıdaki hata mesajlarını veriyor.

```
Warning: preg_replace(): Unknown modifier 'v' in /var/www/html/vendor/izniburak/router/src/Router.php on line 794
Deprecated: explode(): Passing null to parameter #2 ($string) of type string is deprecated in /var/www/html/vendor/izniburak/router/src/Router.php on line 795
```

**Comment by izniburak** [comment]
2.4.1 versiyonuyla beraber, sorunlar giderilmiştir :)

**Comment by ozgurg** [comment]
> 2.4.1 versiyonuyla beraber, sorunlar giderilmiştir :)
> 
> Buna bağlı olarak, paketin testlerini baştan yazmaya başladım ve en kısa zamanda hazır edeceğim. Böylece Github Action ile birlikte testlerin durumunu izleyebileceğiz.
> 
> Bilgilendirmen için teşekkürler!
> 
> @ozgurg ; tekrar denedikten sonra beni yine bilgilendirebilir misin?

Yine düzelmedi ya. Subfolderda hala çalışmıyor ama bu sefer varsayılan hata sayfasındaki HTML gitti, düz metin olarak "Looks like page not found or something went wrong. Please try again." yazıyor.

2.5.0'i de yayınlamışsınız, onda bu sorunla ilgili bir değişiklik yok.

**Comment by izniburak** [comment]
[Changelogs](https://github.com/izniburak/php-router/wiki/Changelogs) dokümanını incelemen fayda verebilir. 
Subfolder mevzusu ile alakalı; v2.5.1 içerisinde bir fix yayınladım. Dilersen tekrar update etmeyi deneyebilirsin.

Umarım bu sorununu çözecektir.

**Comment by ozgurg** [comment]
> [Changelogs](https://github.com/izniburak/php-router/wiki/Changelogs) dokümanını incelemen fayda verebilir. Subfolder mevzusu ile alakalı; v2.5.1 içerisinde bir fix yayınladım. Dilersen tekrar update etmeyi deneyebilirsin.
> 
> Umarım bu sorununu çözecektir.

Özet: Düzeldi, teşekkürler. 😄 


v2.3.3 ile v2.3.4 arasında yapılan değişikliklerin hangisinin bozduğunu tespit ettim.

Tam olarak Router.php getRequestUri() içindeki 

```php
$script = $this->request()->server->get('SCRIPT_NAME');
```

satırı 
```php
$script = $this->request()->server->get('SCRIPT_FILENAME') ?? $this->request()->server->get('SCRIPT_NAME');
```

satırına döndüğü için oluyor. Sadece bu satırı geriye alınca sorun düzeliyor. Ancak bunu yapmadan önce şunu fark ettim. v2.3.3'te ana dizin ve alt dizinde 2 ayrı uygulama çalıştığında alt dizindeki uygulama için `base_folder` ayarlamama gerek kalmadan çalışıyordu. v2.3.4 sonrasında `base_folder`'ı ayarlayınca çalışmaya başladı.
