### ISSUE TITLE
Request Sorunu

### ISSUE THREAD

**Issue by seymennc** [izniburak/php-router#64]
.htaccess ve index.php içine gerekli kodları girmeme rağmen 'Looks like page not found or something went wrong. Please try again.' Hatası alıyorum. Sorun nerede olabilir?

**Comment by osmnaltnsy** [comment]
alt klasörde çalıştırırken bu sorunu yaşıyorsanız aynı sorunu ben de yaşıyorum ve sebebini merak ediyorum. local geliştirme ortamında virtual host oluşturarak ya da php'nin dahili web serverini kullanarak çözdüm ancak örneklerde sorunsuz çalışırken aynı konfigürasyonla bizde niye çalışmıyor acaba?

**Comment by seymennc** [comment]
Ana dizinde çalıştırıyorum ben localde, başka yapanları izliyorum videolarını onlarda olurken bende sorun çıkarıyor. HTTP isteği alınmadığı için olduğunu düşünüyorum ama http isteğinin alınmama gibi bir ihtimali de yok

**Comment by osmnaltnsy** [comment]
ana dizin derken root değil mi? direkt c:\appserv\www içerisinde gibi. eğer öyleyse başka bir sorun var benimki gibi alt dizin sorunu ise şöyle olması gerekiyormuş.
$router = new \Buki\Router\Router([
    'base_folder'=> 'sub\folder'
]);

bu arada mod_rewrite açık mı acaba sizde?

**Comment by seymennc** [comment]
mod_rewrite nereden açılıyor ki

**Comment by izniburak** [comment]
Selamlar,
Server ana dizininde mi kullanıyorsunuz yoksa alt bir klasörde mi? Eğer alt klasörde ise, yeni bir Router instance oluştururken, `base_folder` tanımlaması yapıyor musunuz? [Dokümana](https://github.com/izniburak/php-router/wiki/2.-Getting-Started#other-settings) göz atma şansınız oldu mu? Şimdi yeni bir test proje oluşturup, iki farklı şekilde denedim ama herhangi bir sorun yaşamadım.

**Comment by seymennc** [comment]
Teşekkürler, base_folder ayarlaması ile sorun çözüldü
