### ISSUE TITLE
Route Hata yakalama 

### ISSUE THREAD

**Issue by seymennc** [izniburak/php-router#65]
Kod yazarken herhangi bir hata aldığımda route yapısı sebepsizce devreye girip 'Oops! Something went wrong. Please try again.' şeklinde uyarı geliyor ve ben nerede hata yaptığımı göremiyorum. Örnek olarak veritabanı ekleme işlemlerinde bir yeri eksik yada hatalı yazdığımda o hatayı görmem gerekirken direkt olarak route yapısı devreye girip bu yazıyı yazdırıyor.

**Comment by izniburak** [comment]
Merhabalar,
[Dokümantasyon](https://github.com/izniburak/php-router/wiki/2.-Getting-Started#other-settings) üzerinden `Other Settings` kısmına bakarsanız, orada `debug` parametresi verebiliyorsunuz. Eğer `debug` parametresi `true` olursa, sistemde oluşan tüm hata ve exceptionları görebilirsiniz.
