### ISSUE TITLE
Looks like page not found or something went wrong. Please try again.

### ISSUE THREAD

**Issue by sajjadef98** [izniburak/php-router#67]
hi i use [php-router](https://github.com/izniburak/php-router) in my framework ["flare-framework"](https://github.com/flare-framework/Flare)   but after use composer update and update your packeage my framework don't work  .If you can take a look at it, I really don't know where the problem is

**Comment by peter279k** [comment]
Could you have the steps to install package in the Flare framework?

And it can let others try to reproduce this issue.

**Comment by sajjadef98** [comment]
you can see [Router]([Router.php](https://github.com/flare-framework/Flare/blob/master/Flare/app/Router.php)) and [config]([config.php](https://github.com/flare-framework/Flare/blob/master/Flare/app/config.php))  in dir Flare/app and  index.php and [htaccess]([.htaccess](https://github.com/flare-framework/Flare/blob/master/public/.htaccess)) in public dir you can install that 
composer create-project flare-framework/flare mysite and test its working but after use composer update its show "Looks like page not found or something went wrong. Please try again." ? I really don't know where the problem is 😟☹

**Comment by izniburak** [comment]
Which version of the Router do you use? And what's the previous version?

**Comment by sajjadef98** [comment]
2.3  is working good  but i want use 2.5  you can install and test that

**Comment by izniburak** [comment]
Did you check [changelogs](https://github.com/izniburak/php-router/wiki/Changelogs)?

**Comment by sajjadef98** [comment]
yes , and use
```
 $router->notFound(function(Request $request, Response $response) {
   dump($request,$response) ;
});
```
output ----------------------
[dump($request,$response) 📍](editor://open/?file=C%3A%5Claragon%5Cwww%5Ctp%5Csazman-flare%5C1.0.1%5CFlare%5Capp%5CRouter.php&line=26&search=&replace=)Symfony\Component\HttpFoundation\Request
[dump($request,$response) 📍](editor://open/?file=C%3A%5Claragon%5Cwww%5Ctp%5Csazman-flare%5C1.0.1%5CFlare%5Capp%5CRouter.php&line=26&search=&replace=)Symfony\Component\HttpFoundation\Response
headers: Symfony\Component\HttpFoundation\ResponseHeaderBag
computedCacheControl: array
cookies: array (0)
headerNames: array
headers: array
cacheControl: array (0)
content: ''
version: '1.0'
statusCode: 200
statusText: 'OK'
charset: null
[32.0 ms](http://localhost/tp/sazman-flare/1.0.1/public/index.php#)
[×](http://localhost/tp/sazman-flare/1.0.1/public/index.php#)
---------------------
every request show this message and dont use 
```
$router->get('/', 'EFTEKHARI@index');
// or
$router->get('/sss', function() {
    return 'Hello World.';
});

```
I can't find the problem

**Comment by izniburak** [comment]
Did you set router configs? For ex: base folder?

**Comment by sajjadef98** [comment]
Consider the above messages. You find that this problem is done only with the [composer update ](https://github.com/flare-framework/Flare/blob/master/composer.json)command. So everything is set and it has no problem in version 2.3, but it doesn't work with the update at all.  [Router](https://github.com/flare-framework/Flare/blob/master/Flare/app/Router.php), [index.php](https://github.com/flare-framework/Flare/blob/master/public/index.php) ,[htaccess](https://github.com/flare-framework/Flare/blob/master/public/.htaccess) ,  **Tell me exactly how I can solve the problem ?**

**Comment by izniburak** [comment]
I'll clone your project and try to run it. I need to debug it. I'll inform you about that.

**Comment by omerfdmrl** [comment]
@izniburak any update? I have same error. Is it about php 8? I try [this](https://github.com/tayfunerbilen/php-boilerplate) and it's also not working

**Comment by izniburak** [comment]
Hi, @sajjadef98 and @omerfdmrl ;
I've tried the project and it worked on PHP 8.1.2 (my local env)
The PHP Router version is [v2.5.3](https://packagist.org/packages/izniburak/router#v2.5.3)

Please check Changelogs again and update your code if there is any breaking changes for you.

**Comment by sajjadef98** [comment]
I check that , but not find my problem in my framework its work good in  2.3 but after update its not work?!🤷‍♂️

**Comment by iamserkanyilmaz** [comment]
This problem is usually caused by not being able to find the Controller class.

my files structure
- src
- - Controllers
- - - UserControllers
- routes
- - api.php

my api.php 


`
use Buki\Router\Router;

$router = new Router([
    'paths' => [
        'controllers' => '../src/Controllers',
    ],
    'namespaces' => [
        'controllers' => 'TestAPI\Controllers',
    ],
]);
$router->get('/', 'UserController@test');
$router->run();

`
