### ISSUE TITLE
Add routing react or vue etc.

### ISSUE THREAD

**Issue by bymustfa** [izniburak/php-router#71]
Hello.
First of all, this package is great. However, when we want to install a system such as ractjs or vue js in the frontend of the project, I am not sure how the route structure should be. Do you have any improvement on this?

Example:
```php
$router->get("/", function () { 
   $router->renderPaths("react_path");
});
```

**Comment by izniburak** [comment]
Hi @bymustfa ,
I think it's a specific case for the developers and I'm not sure that should the Router package need to handle the case like that or not. You can define a route and include a view file in that route function. (`include 'public/index.html';`). 
We can discuss about the `View` layer for the Router package, but now we don't support that. If we would add the `View` layer, we can handle these cases.

**Comment by bymustfa** [comment]
Ok tanks👍
