### ISSUE TITLE
WebController class is not found. Please check the file.

### ISSUE THREAD

**Issue by szrcmk** [izniburak/php-router#73]
Merhaba, Localhostta çalışıyordu, sunucuya attığımda bu hatayı almaya başladım. Fakat nasıl sorunu aşacağımı bulamadım. Namespace'ler ile ilgili olduğunu düşündüm ama aynı kodu farklı sunucuda çalıştırabiliyorum. Sunucudan sunucuya nasıl bir farklılık varda böyle bir hata alabiliyorum ?

**Comment by izniburak** [comment]
Merhabalar,

`debug` açarak, detaylı şekilde bir inceleme yapmanız mümkün olabilir. Muhtemelen `base_folder` ile alakalı falan bir sıkıntı olabilir ama, incelemeden bir şey demek zor. Normalde bir hata almamanız lazım çünkü default olarak zaten app'in çalıştığı kök dizini kabul ediyor. Ama nasıl bir configuration kullanıyorsanız, bilemiyorum. Bunlardan kaynaklı bir sıkıntı oluşmuş olabilir.
