### ISSUE TITLE
Router Group kullanarak urlye dil sistemi ekleme

### ISSUE THREAD

**Issue by ahmtcn34** [izniburak/php-router#76]
Url yapısını aşağıdaki resimde göründüğü gibi kurguladım. Normal şekilde dil kısaltması kullanarak sayfalara ulaşabiliyorum. Örnek domain.com/tr. Fakat şöyle bir şey yapmak istiyorum. domain.com/ bu şekilde girilince yani herhangi bir dil kısaltması yoksa urlde otomatik olarak domain.com/tr adresine yönlendirmek istiyorum. Bu yapmak istediğim şey mümkün mü? Kullanım olarak bulamadım.

![image](https://github.com/izniburak/php-router/assets/58213956/7b6f8280-2d5c-42d6-8816-f7aa34cfd339)

**Comment by mehmethcoskun** [comment]
Add a router before pattern definition then redirect to url you wanted.

`$webRouter->router->get('/', function () {
    header("location: https://example.com/tr");
});`

**Comment by ahmtcn34** [comment]
İstediğim tam olarak bu değil. Kullanıcının seçtiği dili alıp urlyi ona göre dinamik yönlendirmek.

**Comment by izniburak** [comment]
Bunun için eklenen custom parametre için default bir değer eklemek gerekiyor ama şu an direkt olarak paket üzerinde bu tarz bir özellik yok. Tavsiyem middleware ile handle edip, ilgili default endpoint'e yönlendirmek olur.

**Comment by mehmethcoskun** [comment]
Middleware ile aşağıdaki şekilde handle edebilirsin dostum.

`<?php

namespace App\Middlewares;

use Symfony\Component\HttpFoundation\Request;

class HandleLocale
{
    public function handle(Request $request)
    {
        $pathInfo = substr($request->getPathInfo(), 1);
        $routerIndexes = array_filter(explode('/', $pathInfo));
        $locale = $routerIndexes[0];
        header("location: https://expamle.com/" . $locale);
    }
}
`

**Comment by ahmtcn34** [comment]
> Middleware ile aşağıdaki şekilde handle edebilirsin dostum.
> 
> `<?php
> 
> namespace App\Middlewares;
> 
> use Symfony\Component\HttpFoundation\Request;
> 
> class HandleLocale { public function handle(Request $request) { $pathInfo = substr($request->getPathInfo(), 1); $routerIndexes = array_filter(explode('/', $pathInfo)); $locale = $routerIndexes[0]; header("location: https://expamle.com/" . $locale); } } `

Yardımınız için teşekkür ederim. Aşağıdaki gibi yaptım şu an sorunsuz çalışıyor. İhtiyacı olan arkadaşlar olursa diye paylaşmak istedim.

![image](https://github.com/izniburak/php-router/assets/58213956/9240b143-3a57-4601-9701-27d7d898ed1c)
