### ISSUE TITLE
Add usage doc

### ISSUE THREAD

**Issue by peter279k** [izniburak/php-router#8]
As title, it needs to do this because I don't really know how to use the route request with `Controller` way.

@izniburak, can you add this usage section firstly? And I can help you to complete the tests for this package :).

**Comment by izniburak** [comment]
@peter279k , I know it, but I haven't had a chance yet. I will try to complete this section in this week. Also, thank you for your contribute about tests.

**Comment by peter279k** [comment]
@izniburak, thank you for your reply. I hope you can complete this section this week at your available time :).

**Comment by bramaudi** [comment]
I can use Controller, just define the path and namespace then mention the namespace in Controller class, done.

Here are example, i create simple prototype using some libs including this router. https://github.com/bramaudi/rongko

**Comment by peter279k** [comment]
@bramaudi, thank you for your reply. I finally find the approach to implement a route with specific `Controller`.

To @izniburak, I also create the elated PR for this issue. Please take look at them.

Thanks :).
